### ISSUE TITLE
Create UI Scaffolding

### ISSUE THREAD

**Issue by jag82** [HannaHoJ/reactOrderTool#4]
Make a skeleton for the app's UI as defined in your offline blue print.

For now, exclude the login. That will be done in its own ticket.

It's likely a placeholder for nav + categories + products + cart + bestaetigung with some simple links between them.  We will then fill out the details as we go along.

**Comment by HannaHoJ** [comment]
added UI components based on offline blue print.
added basic links.
--dynamic linking is not yet implemented--
