### ISSUE TITLE
Placeholder Props for Categories, Products

### ISSUE THREAD

**Issue by jag82** [HannaHoJ/reactOrderTool#7]
You should be able to pass hardcoded data into Categories and Products as props.

Example data:
```
//categories
[ { id: 1, name: 'footwear' }, { id: 2, name: 'watches' } ]

//products
[ { id: 1, name: 'captain crunch sneakers' }, { id: 300, name: 'rocket boots' } ]
```

The rendered UI should be very simple.  For example:
```
<div data-id="1">rocket boots</div>
```
or

```
<a href="/categories/1">footwear</a>
```

**Comment by jag82** [comment]
@HannaHoJ  do this next! before even writing a simple backend

**Comment by HannaHoJ** [comment]
working placeholders in cart, products, category
placeholder data can be found in  /src/product-data.js and /src/order-data.js

**Comment by jag82** [comment]
@HannaHoJ 
It looks good for now, in the near future we will want to make the following changes (you don't have to do them now, but keep them in mind):

Order.totalPrice should be a number instead of a string. Sometimes it's nice to use whole numbers (e.g. 1900 instead of 19,00) to make math easier.

Order.products can be renamed to 'items' or something similar. In  common practice they're referred to as lineitems, a sort of snap shot of a product at the time of purchase (particularly it's price) and the additional info of it's quantity. You basically are already doing this, but I want to avoid future confusion between Products and these Items because of naming.

Product.categories should be an array. A bread may not be able to belong to two categories (or maybe it can?) but other products certainly will.

Nice work in general though, it gets your immediate job done without wandering off topic.
